name: schedule
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  auto_route: ^7.8.3
  flutter_svg: ^2.0.7
  get_it: ^7.6.2
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  syncfusion_flutter_pdfviewer: ^22.2.11
  iso_calendar: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.6
  auto_route_generator: 7.3.1

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf